### ISSUE TITLE
Preact error when using useSwr

### ISSUE THREAD

**Issue by lucis** [denoland/merch#25] opened 2022-08-22 00:12 UTC
## Steps to reproduce
1. Clone repo
2. Configure env vars
3. Run `deno task start` 
4. Access home page

The following issue is happening with me when rendering the home page of the merch store:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/18706156/185817274-7c192d10-215b-4d7b-a953-7dd218fa7a30.png">

```
An error occured during route handling or page rendering. TypeError: Cannot read properties of undefined (reading 'context')
    at j (https://esm.sh/v91/preact@10.8.1/deno/hooks.js:2:1028)
    at br (https://esm.sh/v91/swr@1.3.0/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0L2NvbXBhdA/deno/swr.js:2:6259)
    at https://esm.sh/v91/swr@1.3.0/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0L2NvbXBhdA/deno/swr.js:2:6365
    at useCart (file:///Users/lucis/personal/merch/utils/data.ts:102:10)
    at Object.Cart (file:///Users/lucis/personal/merch/islands/Cart.tsx:47:27)
    at h (https://esm.sh/v91/preact-render-to-string@5.2.0/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:4:1003)
    at h (https://esm.sh/v91/preact-render-to-string@5.2.0/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:9:66)
    at h (https://esm.sh/v91/preact-render-to-string@5.2.0/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:4:1103)
    at h (https://esm.sh/v91/preact-render-to-string@5.2.0/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:9:66)
    at h (https://esm.sh/v91/preact-render-to-string@5.2.0/X-ZS9wcmVhY3Q/deno/preact-render-to-string.js:9:66)
```

I suppose it's something related to the `import_map.json`, but I couldn't pinpoint the problem:

_import_map.json_
```json

{
  "imports": {
    "@/": "./",
    "@twind": "./utils/twind.ts",
    "@twind/aspect-ratio": "https://esm.sh/@twind/aspect-ratio@0.1.4",

    "$fresh/": "https://deno.land/x/fresh@1.0.1/",
    "preact": "https://esm.sh/preact@10.8.1",
    "preact/": "https://esm.sh/preact@10.8.1/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.0?external=preact",

    "twind": "https://esm.sh/twind@0.16.16",
    "twind/": "https://esm.sh/twind@0.16.16/",
    "$std/": "https://deno.land/std@0.149.0/",
    "swr": "https://esm.sh/swr@1.3.0?alias=react:preact/compat&external=preact/compat"
  }
}
```

**Comment by lucis** [comment] 2022-08-22 16:03
Possibly related to https://github.com/vercel/swr/issues/1842

**Comment by cjihrig** [comment] 2022-09-08 16:43
I cannot reproduce this with the latest code (https://github.com/denoland/merch/commit/ede442d96dd2f4e1a1915e05811d9393287d5237). Are you still encountering this problem? Did you make any changes that could be causing the error?

**Comment by cjihrig** [comment] 2022-09-12 17:10
I'm going to close this for now, but please feel free to follow up with my previous comment and we can reopen if necessary.

**Closed by cjihrig** 2022-09-12 17:10 UTC
